Poetry migration
* migrates package management to poetry, updates build config, removes setup.cfg, requirements.txt created programatically

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,15 +1,13 @@
 name: Upload Python Package
 
 on:
-  release:
-    types: [published]
-  push:
-    branhes:
-      - main
-      - issues/69/packaging_and_automation
+  # Allows for manual triggering and pull requests
+  # from every branch, including forks.
+  workflow_dispatch:
+  pull_request:
   
-    
 jobs:
+  # Flake8 & Pytest
   lint_and_test:
     runs-on: ubuntu-latest
     strategy:
@@ -21,38 +19,53 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install flake8 pytest
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-      - name: Lint with flake8
-        run: |
-          # stop the build if there are Python syntax errors or undefined names
-          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-      - name: Test with pytest
-        run: |
-          pytest
 
+      - name: Lint
+        run: |
+          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
+          source $HOME/.poetry/env
+          poetry install
+          # stop the build if there are Python syntax errors or undefined 
+          echo "Flake8 Syntax Error Check"
+          poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
+          # stop the build if the conventions in .flake8 fail
+          poetry run flake8
+      
+      - name: Test
+        run: |
+          source $HOME/.poetry/env
+          poetry run pytest
+
+  # Publish to Pypi
   build_and_release:
     runs-on: ubuntu-latest
     needs: lint_and_test
+    if: github.ref == 'refs/heads/issues/69/packaging_and_automation'
     steps:
       - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0 # Gets all tags and repo history
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
-      - name: Install dependencies
+      
+      - name: Version
         run: |
-          python -m pip install --upgrade pip
-          pip install build
-      - name: Build package
-        run: python -m build
-      - name: Publish package
-        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
+          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
+          source $HOME/.poetry/env
+          # set version number equal to latest git tag
+          poetry version $(git describe --tags | head -n 1') || echo "Version System Error" && exit 1
+
+      - name: Build & Publish package
+        run: |
+          source $HOME/.poetry/env
+          poetry config repositories.testpypi https://test.pypi.org/legacy/
+          poetry publish --build -r testpypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}
+
+      - name: Create GitHub Release
+        uses: ncipollo/release-action@v1
         with:
-          user: __token__
-          password: ${{ secrets.PYPI_API_TOKEN }}
+          artifacts: "dist/*"
+          bodyFile: "README.md"
+          token: ${{ secrets.GITHUB_TOKEN }}
